version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    environment:
      MONGO_URI: "mongodb://mongo:27017/palooza"
    ports:
      - "3066:3066"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
