name: Build and Lint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or any version you prefer

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint # Assuming you have a lint script in your package.json

    - name: Build
      run: npm run build # Assuming you have a build script in your package.json
